name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        combo:
        - otp-version: '25.2'
          rebar3-version: '3.18.0'
        - otp-version: '26.2'
          rebar3-version: '3.23.0'
        - otp-version: '27.2'
          rebar3-version: '3.24.0'
        - otp-version: '28.0'
          rebar3-version: '3.25.0'
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1.18
        with:
          otp-version: ${{ matrix.combo.otp-version }}
          rebar3-version: ${{ matrix.combo.rebar3-version }}

      - uses: actions/cache@v4
        id: rebar3-cache
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.combo.otp-version }}-${{ matrix.combo.rebar3-version }}-${{ hashFiles('rebar.lock') }}

      - run: rebar3 check

      - run: rebar3 compile

      - run: rebar3 test

      - uses: test-summary/action@v2
        if: always()
        with:
          paths: '_build/test/logs/**/report.xml'
